name: berlin-tdd-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.0.4
  - jupyterlab=2.1.4
  - matplotlib=3.2.0
  - seaborn
  - jupyter=1.0.0
  - seaborn
  - pytest
  - pytest-cov
  - pandas-profiling=2.8.0
  - python=3.7
