name: berlin-tdd-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.0.1
  - jupyterlab=2.01
  - matplotlib=3.2.0
  - seaborn
  - jupyter
  - seaborn
  - pytest
  - pytest-cov
  - pandas-profiling=2.8.0
  - python=3.7
